#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=phi4_esnli
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=16:00:00
#SBATCH --output=phi4_100_esnli_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

cd $HOME/FACT-AI/CC-SHAP/

source activate fact2

srun python3 faithfulness.py esnli phi4 100 "partition" 500 0.5 --result_dir="main_results_json"
