#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=phi4_qa
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=16:00:00
#SBATCH --output=phi4_100_qa_loo%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

cd $HOME/FACT-AI/CC-SHAP/

source activate fact2

srun python3 faithfulness.py disambiguation_qa phi4 100 "partition" 500 0.68 --result_dir="loo_test"
