#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=Falcon3_comve
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=10:00:00
#SBATCH --output=falcon3_100_comve_loo_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

cd $HOME/FACT-AI/CC-SHAP/

source activate fact2

srun python3 faithfulness.py comve falcon3-7B-chat 100 "partition" 500 0.68 --result_dir="loo_test"
