#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=falcon
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:09:59
#SBATCH --output=falcon_output_loo_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

cd $HOME/FACT-AI/CC-SHAP/

source activate fact

srun python3 faithfulness.py comve falcon-7b-chat 1 "partition" 500 0.68 --result_dir="loo_test"
